a=int(input("Enter first number :"))
b=int(input("Enter second number :"))
print("The sum of",a, "and" ,b, "is:",a+b)
print("The subtraction of",a, "and" ,b, "is:",a-b)
print("The division of",a, "and" ,b, "is:",a/b)
print("The modulus of",a, "and" ,b, "is:",a%b)
print("The floor division of",a, "and" ,b, "is:",a//b)